### PR TITLE
Raw analysis upgrades

### PR DESCRIPTION
**Pull request by jgalan**
jgalan  [](https://gitlab.cern.ch/rest-for-physics/rawlib/-/commits/raw_analysis_upgrades) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=rest-for-physics&utm_campaign=badge_info)

TRestRawSignalAnalysisProcess.
* Added a new observable map to register the peak time of each pulse, `peak_time_map`.
* Added a new metadata parameter `fSignalsRange` allowing to apply the analysis to the given signal ids range.

TRestRawSignalRemoveChannelsProcess
* Added a new parameter `removeChannels` allowing to remove a range of channels.

This should allow to launch the analysis of veto signals.

For example using the following data chain:

```
TRestRawSignalAnalysisProcess (vetoAna) --> TRestRawRemoveChannelsProcess --> TRestRawSignalAnalysisProcess (rawAna)
```

We may implement as follows to analyse the veto channels that would be in the daq id range (X,Y):

```
<addProcess type="TRestRawSignalAnalysisProcess" name="vetoAna" value="ON" ... signalsRange="(X,Y)" ...>

       <observable name="max_amplitude_map" type="map<int,double>" value="ON" />
       <observable name="peak_time_map" type="map<int,int>" value="ON" />
</addProcess>

<addProcess type="TRestRawSignalRemoveChannelsProcess" name="rmChannels" value="ON">
          <removeChannels range="(X,Y)" />
</addProcess>

<addProcess type="TRestRawSignalAnalysisProcess" name="rawAna" value="ON" ...>

       ... usual micromegas analysis ...
      
</addProcess>

```

That will fill the analysis tree with all the veto channels, amplitude + peak_time.

That will make it more clean at the analysis_tree, and on top of that we can get any additional observable that we can get using `TRestRawSignalAnalysisProcess`. As the RML was written above, only `max_amplitude_map` and `peak_time_map` should be written to the analysis tree.

I didnt test the present changes are working properly, just building test.

### CODE REVIEW

**Comment by jgalan** [comment]
As discussed with @KonradAltenmueller offline, we could then define a generic `TRestMapGroups` metadata class at the main framework. This class would be a helper class to allow to define any group ids through RML.

We could have another generic process, i.e. `TRestMapAnalysisProcess` that would use that `TRestMapGroups` to create new observables.

So that for example, if my group has a given ids, it will calculate the average, or the max, or any other mathematical artifact as defined by the user, and it will create an observable as:

`pcsName_groupName_average`, `pcsName_groupName_max`, ...

This process may be connected at any stage of the processing and it may be applied to any map observable to generate additional prebuilt observables ready at the analysisTree.

**Comment by jgalan** [comment]
I added a validation pipeline at `processes/analysis` using the veto scheme in the description of this PR.

**Comment by jgalan** [comment]
Hi @nkx, we are running into troubles again with the `map<int,double>` issue. 

https://gitlab.cern.ch/rest-for-physics/rawlib/-/jobs/14353889

There is any trick to solve this inside the macro and fix this problem?

**Comment by nkx111** [comment]
I see, somehow the typeinfo becomes null after initializing the reflector from typename. I have fixed that problem and made a pull request

**Comment by jgalan** [comment]
Plz, approve rest-for-physics/framework#61 to fix this pipeline

**Review by juanangp — APPROVED** [review]

**Review by KonradAltenmueller — APPROVED** [review]

**Review by juanangp — APPROVED** [review]

**Comment by jgalan** [comment]
Ok, pipeline is passing now. I believe these changes can be approved.

**Pull request merged**
