### PR TITLE
Adding new method to draw signals in TRestRawSignalEvent

### PR DESCRIPTION
**Pull request by juanangp**
juanangp Medium: 113 [](https://gitlab.cern.ch/rest-for-physics/rawlib/-/commits/alphaAna) [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/alphaAna)

Adding new method to draw a `vector` or signal IDs in  TRestRawSignalEvent

### CODE REVIEW

**Review by nkx111 — COMMENTED** [review]
Where is the new `TRestRawZeroSuppresionProcess` in the lib? There is only `TRestRawSignalEvent` being changed

**Comment by jgalan** [comment]
Probably the new implemented method should be used by `TRestRawSignalEvent::DrawEvent` under a particular option being passed?

**Comment by juanangp** [comment]
> Probably the new implemented method should be used by `TRestRawSignalEvent::DrawEvent` under a particular option being passed?

Now `TRestRawSignalEvent::DrawEvent` calls `TRestRawSignalEvent::DrawSignals` for the drawing of the pulses, previous functionality is kept.

**Review by jgalan — APPROVED** [review]

**Comment by juanangp** [comment]
> Since you re-furbished the DrawEvent method you probably have at hand a nice plot that could be added to the `TRestRawSignalEvent` documentation?
> 
> I am successful adding images in doxygen with the following recipe:
> 
> ```
> /// \htmlonly <style>div.image img[src="image.png"]{width:750px;}</style> \endhtmlonly
> ///
> /// A text as the title of the image
> ```

I am not sure how to upload de image, find it below

image

**Comment by jgalan** [comment]
The image must be placed at the `images` directory. Then, it will be found by `doc/doxygen/REST.conf` when executing doxygen.

**Pull request merged**
