### PR TITLE
General fit

### PR DESCRIPTION
**Pull request by DavidDiezIb**
Large DavidDiezIb  [](https://gitlab.cern.ch/rest-for-physics/rawlib/-/commits/generalFit) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=rest-for-physics&utm_campaign=badge_info)

### CODE REVIEW

**Comment by jgalan** [comment]
Do you have still the planning to merge all the Fitting processes into a single `TRestRawSignalFittingProcess`? I understand for the moment you need to write down the `General` keyword at the process name, but then it could be abbreviated to just `TRestRawSignalFittingProcess`?

**Comment by DavidDiezIb** [comment]
Yes, right now GeneralFitProcess can do everything that FittingProcess does, so this can be removed. 
There are two other processes related, ConvolutionFittingProcess and FitEventProcess, which is the merge of ConvolutionFittingProcess and FittingProcess. My idea is to do the same as I've done for GeneralFitProcess, implement a way to read the functions and parameters from the rml, so we'll end up with at most two processes, one to fit with single function and other to fit with the convolution of two.

**Comment by jgalan** [comment]
One could even think that the fit with single function is a particular case, Dirac delta, of the convolution fitting to unify into one process.

**Comment by jgalan** [comment]
In any case, for this PR the pipeline is already green, so it is fine to merge to master.

**Review by jgalan — APPROVED** [review]

**Comment by DavidDiezIb** [comment]
> 
> 
> One could even think that the fit with single function is a particular case, Dirac delta, of the convolution fitting to unify into one process.

I'm afraid the fitting process doesn't work as fine as expected with this trick, but it's something I have to try.

**Review by juanangp — APPROVED** [review]

**Pull request merged**
