### PR TITLE
Adding veto validation pipeline

### PR DESCRIPTION
**Pull request by jgalan**
jgalan  [](https://gitlab.cern.ch/rest-for-physics/rawlib/-/commits/iaxo-veto-validation) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=rest-for-physics&utm_campaign=badge_info)

A simplified validation pipeline version, extracted from rest-for-physics/framework#51

### CODE REVIEW

**Review by KonradAltenmueller — APPROVED** [review]

**Review by DavidDiezIb — APPROVED** [review]

**Comment by jgalan** [comment]
@KonradAltenmueller and @DavidDiezIb you approved to early, the pipeline is failing!

See the red pipeline:failed at the header of this PR?

@nkx I dont understand why the segmentation fault. I cannot reproduce it locally.

**Comment by jgalan** [comment]
I was trying to find out the source of the problem at the pipeline. I could reproduce the problem locally when compiling REST just with the rawlib, as it is done at the pipeline.

Then, tracing to see where it crashes I got it does at the `ProcessEvent` call inside `TRestThread::TestRun`.

It is really strange, @nkx do you know the meaning of ```Loading external dictionary for: "map<int,double>": /home/jgalan/.rest/AddonDict/Dict_map_int_double_.so``` it is the first time I see that 

```
-- Debug : Entering TRestEventProcess::EndOfEventProcess (TRestRawMultiFEMINOSToSignalProcess)
-- Debug : TRestThread: Init process...
-- Debug : InitProcess() process for TRestRawVetoAnalysisProcess
-- Debug : Test Run...
-- Debug : Processing ...
-- Debug : Test run 0 : Input Event ---- TRestRawSignalEvent(0x55a76107e920)
-- Debug : t0p0: TRestRawVetoAnalysisProcess
-- Debug : TRestThread::TestRun. Process : 0. BeginOfEventProcess
-- Debug : TRestThread::TestRun. Process : 0. ProcessEvent
-- Debug : TRestThread::TestRun. Process pointer before: ProcessEvent: 0x55a760e57e00
-- Debug : TRestThread::TestRun. Process name: veto
TRestRawVetoAnalysisProcess::ProcessEvent. ID: 1
Loading external dictionary for: "map<int,double>":
/home/jgalan/.rest/AddonDict/Dict_map_int_double_.so

 *** Break *** segmentation violation




===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f9e843e404a in __GI___waitpid (pid=23341, stat_loc=stat_loc
entry=0x7fff5c947e40, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00007f9e8436b0ab in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00007f9e8ab18917 in TUnixSystem::StackTrace() () from /programas/root/root-6.20/lib/libCore.so
#3  0x00007f9e8ab1b064 in TUnixSystem::DispatchSignals(ESignals) () from /programas/root/root-6.20/lib/libCore.so
#4  <signal handler called>
#5  strlen () at ../sysdeps/x86_64/strlen.S:106
#6  0x00007f9e6da4b96e in REST_Reflection::TRestReflector::TRestReflector<std::map<int, double, std::less<int>, std::allocator<std::pair<int const, double> > > >(std::map<int, double, std::less<int>, std::allocator<std::pair<int const, double> > > const&) () from /programas/REST/dev_javi/lib/libRestRaw.so
#7  0x00007f9e6da4d529 in void TRestEventProcess::SetObservableValue<std::map<int, double, std::less<int>, std::allocator<std::pair<int const, double> > > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<int, double, std::less<int>, std::allocator<std::pair<int const, double> > > const&) () from /programas/REST/dev_javi/lib/libRestRaw.so
#8  0x00007f9e6da7b46a in TRestRawVetoAnalysisProcess::ProcessEvent(TRestEvent*) () from /programas/REST/dev_javi/lib/libRestRaw.so
#9  0x00007f9e8b0b680b in TRestThread::TestRun() () from /programas/REST/dev_javi/lib/libRestFramework.so
#10 0x00007f9e8b0ba4e5 in TRestThread::PrepareToProcess(bool*) () from /programas/REST/dev_javi/lib/libRestFramework.so
#11 0x00007f9e8b09766b in TRestProcessRunner::RunProcess() () from /programas/REST/dev_javi/lib/libRestFramework.so
#12 0x00007f9e8b05890c in TRestManager::ReadConfig(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TiXmlElement*) () from /programas/REST/dev_javi/lib/libRestFramework.so
#13 0x00007f9e8b0598e3 in TRestManager::InitFromConfigFile() () from /programas/REST/dev_javi/lib/libRestFramework.so
#14 0x00007f9e8b06c04c in TRestMetadata::LoadConfigFromElement(TiXmlElement*, TiXmlElement*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >) () from /programas/REST/dev_javi/lib/libRestFramework.so
#15 0x00007f9e8b07542b in TRestMetadata::LoadConfigFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /programas/REST/dev_javi/lib/libRestFramework.so
#16 0x000055a75e7bdf59 in main ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  strlen () at ../sysdeps/x86_64/strlen.S:106
#6  0x00007f9e6da4b96e in REST_Reflection::TRestReflector::TRestReflector<std::map<int, double, std::less<int>, std::allocator<std::pair<int const, double> > > >(std::map<int, double, std::less<int>, std::allocator<std::pair<int const, double> > > const&) () from /programas/REST/dev_javi/lib/libRestRaw.so
#7  0x00007f9e6da4d529 in void TRestEventProcess::SetObservableValue<std::map<int, double, std::less<int>, std::allocator<std::pair<int const, double> > > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<int, double, std::less<int>, std::allocator<std::pair<int const, double> > > const&) () from /programas/REST/dev_javi/lib/libRestRaw.so
#8  0x00007f9e6da7b46a in TRestRawVetoAnalysisProcess::ProcessEvent(TRestEvent*) () from /programas/REST/dev_javi/lib/libRestRaw.so
#9  0x00007f9e8b0b680b in TRestThread::TestRun() () from /programas/REST/dev_javi/lib/libRestFramework.so
#10 0x00007f9e8b0ba4e5 in TRestThread::PrepareToProcess(bool*) () from /programas/REST/dev_javi/lib/libRestFramework.so
#11 0x00007f9e8b09766b in TRestProcessRunner::RunProcess() () from /programas/REST/dev_javi/lib/libRestFramework.so
#12 0x00007f9e8b05890c in TRestManager::ReadConfig(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TiXmlElement*) () from /programas/REST/dev_javi/lib/libRestFramework.so
#13 0x00007f9e8b0598e3 in TRestManager::InitFromConfigFile() () from /programas/REST/dev_javi/lib/libRestFramework.so
#14 0x00007f9e8b06c04c in TRestMetadata::LoadConfigFromElement(TiXmlElement*, TiXmlElement*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >) () from /programas/REST/dev_javi/lib/libRestFramework.so
#15 0x00007f9e8b07542b in TRestMetadata::LoadConfigFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /programas/REST/dev_javi/lib/libRestFramework.so
#16 0x000055a75e7bdf59 in main ()
===========================================================
```

**Comment by jgalan** [comment]
I started to track deeper, and found that those lines come out when the following code executes inside `TRestRawVetoAnalysisProcess`.

```
SetObservableValue(fPeakTime[i], VetoPeakTime_map);
```
I added few debuging output lines that print the following.
```
-- Debug : F1.PeakTime_top
Loading external dictionary for: "map<int,double>":
/home/jgalan/.rest/AddonDict/Dict_map_int_double_.so
-- Debug : F2.MaxPeakAmplitude_top
```

I see the implementation is very similar to `TRestRawSignalAnalysisProcess` and if I replace the `TRestRawVetoAnalysisProcess` by `TRestRawSignalAnalysisProcess` problem also appears.

There is some additional linking added to `detector,track,xx` lib so that this problem is avoided when linking to other libraries?

**Comment by jgalan** [comment]
The problem seems related to reflection methods, since the problem appears when `SetObservableValue` is called.

It is surprising that when I add the detectorlib to be compiled, the problem will disappear.

https://gitlab.cern.ch/rest-for-physics/rawlib/-/pipelines/2652953

@nkx do you see a reason why this happens?

**Comment by nkx111** [comment]
`Loading external dictionary for: "map<int,double>"` is a feature introduced by me. I know it.

The reason to add this is to make it possible to write map objects to TTree. In pure root environment it cannot add map as the tree's branch directly.

```
root [0] map<int,double> mm
(std::map<int, double> &) {}
root [1] TTree*tree=new TTree();
root [2] tree->Branch("map",&mm)
Error in <TTree::Branch>: The class requested (map<int,double>) for the branch "map" is an instance of an stl collection and does not have a compiled CollectionProxy. Please generate the dictionary for this collection (map<int,double>) to avoid to write corrupted data.
(TBranch *) nullptr
```

So I added a check to make it automatically generate a "compiled CollectionProxy" if we want to add a map object as tree's branch. **But it seems to be not working normally in the pipeline.**

The reason why that linking `detectorlib` solves the problem is because that this library contains the "compiled CollectionProxy" for map<int,double>. It is contained in a class's ROOT dict which contains map<int,double> as the class member. Therefore we don't need to generate the "compiled CollectionProxy" when creating branch.

**Comment by jgalan** [comment]
> `Loading external dictionary for: "map<int,double>"` is a feature introduced by me. I know it.
> 
> The reason to add this is to make it possible to write map objects to TTree. In pure root environment we cannot directly add `map` as the tree's branch.
> 
> ```
> root [0] map<int,double> mm
> (std::map<int, double> &) {}
> root [1] TTree*tree=new TTree();
> root [2] tree->Branch("map",&mm)
> Error in <TTree::Branch>: The class requested (map<int,double>) for the branch "map" is an instance of an stl collection and does not have a compiled CollectionProxy. Please generate the dictionary for this collection (map<int,double>) to avoid to write corrupted data.
> (TBranch *) nullptr
> ```
> 
> So I added a check to make it automatically generate a "compiled CollectionProxy" if we want to add a map object as tree's branch. **But it seems to be not working normally in the pipeline.**
> 
> The reason why that linking `detectorlib` solves the problem is because that this library contains the "compiled CollectionProxy" for map<int,double>. It is contained in a class's ROOT dict which contains map<int,double> as the class member. Therefore we don't need to generate the "compiled CollectionProxy" when creating branch.

Ok, so it is possible to include the "compiled CollectionProxy" for map<int,double> directly at the `framework`?

**Comment by nkx111** [comment]
Yes, to include "compiled CollectionProxy" solves the problems quickly. But I need to figure out why it is failing to generate dictionary during the runtime. It was working when I added this feature years ago. In future someone may save map<int, float> to the branch and again get troubled by this seg.fault.

**Comment by jgalan** [comment]
Ok, then create an issue at the framework about that, and lets have that "solved" temporally for the libraries pipelines.

**Comment by nkx111** [comment]
I think the bug has been fixed

**Review by nkx111 — APPROVED** [review]

**Comment by jgalan** [comment]
Hi @nkx, PR rest-for-physics/framework#54 needs to be merged so that this pipeline will succeed.

You need to add reviewers so that it is approved and we are allowed to merge it.

**Pull request merged**
